//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MdSearch_1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangesHistory
    {
        public int ChangeID { get; set; }
        public int FileID { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public string ChangeDescription { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
        public string ChangeType { get; set; }
    
        public virtual Files Files { get; set; }
    }
}
