//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MdSearch_1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documents
    {
        public int DocumentID { get; set; }
        public Nullable<int> FileID { get; set; }
        public string Encoding { get; set; }
        public Nullable<int> PageCount { get; set; }
        public Nullable<int> LineCount { get; set; }
        public string Language { get; set; }
        public string Version { get; set; }
        public Nullable<int> ColumnCount { get; set; }
        public Nullable<int> FormulaCount { get; set; }
        public Nullable<int> ImageCount { get; set; }
        public Nullable<int> TableCount { get; set; }
        public Nullable<int> SymbolCountWithSpaces { get; set; }
        public Nullable<int> SymbolCountWithoutSpaces { get; set; }
        public Nullable<int> WordCount { get; set; }
        public string Creator { get; set; }
    
        public virtual Files Files { get; set; }
        public virtual Files Files1 { get; set; }
    }
}
