//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MdSearch_1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Images
    {
        public int ImageID { get; set; }
        public Nullable<int> FileID { get; set; }
        public string Resolution { get; set; }
        public Nullable<int> ColorDepth { get; set; }
        public string Orientation { get; set; }
        public string PreviewImage { get; set; }
        public string CompressionLevel { get; set; }
        public string ColorProfile { get; set; }
        public string ScalingLevel { get; set; }
        public string CameraModel { get; set; }
        public string Geolocation { get; set; }
        public string Creator { get; set; }
    
        public virtual Files Files { get; set; }
        public virtual Files Files1 { get; set; }
    }
}
