//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MdSearch_1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reports
    {
        public int ReportID { get; set; }
        public Nullable<int> FileID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string ReportData { get; set; }
        public string ReportType { get; set; }
        public string ReportPath { get; set; }
    
        public virtual Files Files { get; set; }
        public virtual Files Files1 { get; set; }
    }
}
