//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MdSearch_1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPermissions
    {
        public int PermissionID { get; set; }
        public int UserID { get; set; }
        public bool CanEditMetadata { get; set; }
        public bool CanDeleteAll { get; set; }
        public bool CanClearHistory { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
