//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MdSearch_1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoFiles
    {
        public int VideoFileID { get; set; }
        public Nullable<int> FileID { get; set; }
        public Nullable<double> Duration { get; set; }
        public string Resolution { get; set; }
        public Nullable<double> FrameRate { get; set; }
        public string VideoCodec { get; set; }
        public string AudioCodec { get; set; }
        public Nullable<int> AudioTrack { get; set; }
        public Nullable<int> SampleRate { get; set; }
        public Nullable<int> ReleaseYear { get; set; }
        public string Description { get; set; }
        public string PreviewImage { get; set; }
        public Nullable<int> DataTransferRate { get; set; }
        public Nullable<int> TotalBitrate { get; set; }
        public string Genre { get; set; }
    
        public virtual Files Files { get; set; }
        public virtual Files Files1 { get; set; }
    }
}
